export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.urbanvana.com"
export const SITE_NAME = "Urbanvana"
export const SITE_DESCRIPTION = "Aeroponic towers for Indian homes. Grow methi, palak, coriander on your balcony — no soil, no expertise. First harvest in 3 weeks."
export const DEFAULT_OG_IMAGE = "/hero-section.png"
export const CONTACT_EMAIL = "urbanvana.co@gmail.com"
export const CONTACT_PHONE = "+91 97127 79666"
